// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThreatCastPK.Database.Context;

#nullable disable

namespace ThreatCastPK.Database.Migrations
{
    [DbContext(typeof(ThreatCastDbContext))]
    partial class ThreatCastDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

<<<<<<< HEAD
=======
            modelBuilder.Entity("SectorRiskScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("EventCount24h")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastCalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SectorName")
                        .IsUnique();

                    b.ToTable("SectorRiskScores");
                });

            modelBuilder.Entity("ThreatAdvisory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("AffectedCities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AffectedSectors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeverityTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("ThreatAdvisories");
                });

>>>>>>> haadi-cyber
            modelBuilder.Entity("ThreatCastPK.Database.Models.AlertSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AttackTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MinimumSeverity")
                        .HasColumnType("integer");

                    b.Property<string>("Sectors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AlertSubscriptions");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.AttackEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AttackType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfidenceTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetSector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("AttackEvents");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.AttackReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AttackType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfidenceTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("SourceIP")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetSector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ReporterId");

                    b.ToTable("AttackReports");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("TargetEntity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.DiscussionPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
<<<<<<< HEAD
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");
=======
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");
>>>>>>> haadi-cyber

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

<<<<<<< HEAD
=======
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

>>>>>>> haadi-cyber
                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

<<<<<<< HEAD
                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp with time zone");
=======
                    b.Property<Guid?>("ParentPostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");
>>>>>>> haadi-cyber

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

<<<<<<< HEAD
                    b.HasKey("Id");

                    b.HasIndex("UserId");

=======
                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentPostId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

>>>>>>> haadi-cyber
                    b.ToTable("DiscussionPosts");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
<<<<<<< HEAD
=======

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a3dce2d-0a91-4f9c-9c6d-4c0b0b3f2c01"),
                            CityName = "Karachi",
                            Latitude = 24.860700000000001,
                            Longitude = 67.001099999999994,
                            Province = "Sindh"
                        },
                        new
                        {
                            Id = new Guid("9a1d4570-4b62-4a6d-86bb-5c9d5c5a9c02"),
                            CityName = "Lahore",
                            Latitude = 31.520399999999999,
                            Longitude = 74.358699999999999,
                            Province = "Punjab"
                        },
                        new
                        {
                            Id = new Guid("b0c39e1f-ef6f-41b1-8d7b-3c5aa1f0e003"),
                            CityName = "Islamabad",
                            Latitude = 33.684399999999997,
                            Longitude = 73.047899999999998,
                            Province = "Islamabad Capital Territory"
                        },
                        new
                        {
                            Id = new Guid("d2a2c9a4-5a0a-4b82-a6e5-2f1b8c1c5004"),
                            CityName = "Rawalpindi",
                            Latitude = 33.565100000000001,
                            Longitude = 73.016900000000007,
                            Province = "Punjab"
                        },
                        new
                        {
                            Id = new Guid("e8b6c5f4-1c9a-4c12-9d6a-2b8f25d6e005"),
                            CityName = "Faisalabad",
                            Latitude = 31.450399999999998,
                            Longitude = 73.135000000000005,
                            Province = "Punjab"
                        },
                        new
                        {
                            Id = new Guid("7f78f3a4-58a6-4cf1-8f2b-9e0f2c3a6006"),
                            CityName = "Multan",
                            Latitude = 30.157499999999999,
                            Longitude = 71.524900000000002,
                            Province = "Punjab"
                        },
                        new
                        {
                            Id = new Guid("2c72a6e8-1a6e-4ec8-8c3f-1a8b5c7a7007"),
                            CityName = "Peshawar",
                            Latitude = 34.015099999999997,
                            Longitude = 71.580500000000001,
                            Province = "Khyber Pakhtunkhwa"
                        },
                        new
                        {
                            Id = new Guid("51c8a5d6-65d2-44d6-a1e9-5f3d2a8b8008"),
                            CityName = "Quetta",
                            Latitude = 30.1798,
                            Longitude = 66.974999999999994,
                            Province = "Balochistan"
                        },
                        new
                        {
                            Id = new Guid("f4a86b77-0d9f-4c76-9f2f-9b7e8b6c9009"),
                            CityName = "Hyderabad",
                            Latitude = 25.396000000000001,
                            Longitude = 68.357799999999997,
                            Province = "Sindh"
                        },
                        new
                        {
                            Id = new Guid("c9a7e2b1-6e3a-4e69-8b2f-6d6c7a7f0010"),
                            CityName = "Gujranwala",
                            Latitude = 32.1877,
                            Longitude = 74.194500000000005,
                            Province = "Punjab"
                        },
                        new
                        {
                            Id = new Guid("6d1c9f83-4c4c-4f8a-8ad9-1c2d3e4f1011"),
                            CityName = "Sialkot",
                            Latitude = 32.494500000000002,
                            Longitude = 74.522900000000007,
                            Province = "Punjab"
                        },
                        new
                        {
                            Id = new Guid("ab93c7b8-1f2c-4a66-9e2a-7c8d9e0f1212"),
                            CityName = "Abbottabad",
                            Latitude = 34.146299999999997,
                            Longitude = 73.211699999999993,
                            Province = "Khyber Pakhtunkhwa"
                        });
>>>>>>> haadi-cyber
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

<<<<<<< HEAD
            modelBuilder.Entity("ThreatCastPK.Database.Models.SectorRiskScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SectorName")
                        .IsUnique();

                    b.ToTable("SectorRiskScores");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.ThreatAdvisory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("AffectedSectors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeverityTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("ThreatAdvisories");
                });

=======
>>>>>>> haadi-cyber
            modelBuilder.Entity("ThreatCastPK.Database.Models.ThreatCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AffectedCities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AffectedSectors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlertLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ThreatCampaigns");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<bool>("ReporterRequestPending")
                        .HasColumnType("boolean");

                    b.Property<int>("ReputationScore")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

<<<<<<< HEAD
=======
            modelBuilder.Entity("ThreatAdvisory", b =>
                {
                    b.HasOne("ThreatCastPK.Database.Models.User", "Admin")
                        .WithMany("ThreatAdvisories")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

>>>>>>> haadi-cyber
            modelBuilder.Entity("ThreatCastPK.Database.Models.AlertSubscription", b =>
                {
                    b.HasOne("ThreatCastPK.Database.Models.User", "User")
                        .WithMany("AlertSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.AttackEvent", b =>
                {
                    b.HasOne("ThreatCastPK.Database.Models.ThreatCampaign", "ThreatCampaign")
                        .WithMany("AttackEvents")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThreatCastPK.Database.Models.Location", "Location")
                        .WithMany("AttackEvents")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThreatCastPK.Database.Models.AttackReport", "AttackReport")
                        .WithOne("AttackEvent")
                        .HasForeignKey("ThreatCastPK.Database.Models.AttackEvent", "ReportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AttackReport");

                    b.Navigation("Location");

                    b.Navigation("ThreatCampaign");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.AttackReport", b =>
                {
                    b.HasOne("ThreatCastPK.Database.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThreatCastPK.Database.Models.User", "Reporter")
                        .WithMany("AttackReports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.AuditLog", b =>
                {
                    b.HasOne("ThreatCastPK.Database.Models.User", "Admin")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.DiscussionPost", b =>
                {
<<<<<<< HEAD
                    b.HasOne("ThreatCastPK.Database.Models.User", "User")
                        .WithMany("DiscussionPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

=======
                    b.HasOne("ThreatCastPK.Database.Models.DiscussionPost", "ParentPost")
                        .WithMany()
                        .HasForeignKey("ParentPostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThreatCastPK.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThreatCastPK.Database.Models.User", null)
                        .WithMany("DiscussionPosts")
                        .HasForeignKey("UserId1");

                    b.Navigation("ParentPost");

>>>>>>> haadi-cyber
                    b.Navigation("User");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.Notification", b =>
                {
                    b.HasOne("ThreatCastPK.Database.Models.AlertSubscription", "AlertSubscription")
                        .WithMany("Notifications")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThreatCastPK.Database.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertSubscription");

                    b.Navigation("User");
                });

<<<<<<< HEAD
            modelBuilder.Entity("ThreatCastPK.Database.Models.ThreatAdvisory", b =>
                {
                    b.HasOne("ThreatCastPK.Database.Models.User", "Admin")
                        .WithMany("ThreatAdvisories")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

=======
>>>>>>> haadi-cyber
            modelBuilder.Entity("ThreatCastPK.Database.Models.AlertSubscription", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.AttackReport", b =>
                {
                    b.Navigation("AttackEvent");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.Location", b =>
                {
                    b.Navigation("AttackEvents");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.ThreatCampaign", b =>
                {
                    b.Navigation("AttackEvents");
                });

            modelBuilder.Entity("ThreatCastPK.Database.Models.User", b =>
                {
                    b.Navigation("AlertSubscriptions");

                    b.Navigation("AttackReports");

                    b.Navigation("AuditLogs");

                    b.Navigation("DiscussionPosts");

                    b.Navigation("Notifications");

                    b.Navigation("ThreatAdvisories");
                });
#pragma warning restore 612, 618
        }
    }
}
