name: Build and deploy API to Azure - threatcastpk-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore
        run: dotnet restore "ThreatCastPK.API/ThreatCastPK.API.csproj"

      - name: Build
        run: dotnet build "ThreatCastPK.API/ThreatCastPK.API.csproj" --configuration Release --no-restore

      - name: Publish
        run: dotnet publish "ThreatCastPK.API/ThreatCastPK.API.csproj" --configuration Release --no-build --output ./published/api

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: ./published/api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-app
          path: ./published/api

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7218FC559E2C405593156FB3B0C04B21 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_23B4E0C2FACF49159EFED72D7DCFEE42 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A8D1676290F04C9B91D73630AA85BFEF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'threatcastpk-api'
          slot-name: 'Production'
          package: ./published/api